language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
install:
    - pip install zope.testrunner coverage coveralls
    - pip install -e .
script:
    - coverage run --source=irclog2html -m zope.testrunner.__init__ --test-path=src
after_script:
    - coveralls
notifications:
    email: false
