language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - pypy
install:
    - pip install zope.testrunner coverage coveralls --use-mirrors
    - pip install -e .
script:
    - coverage run zope-testrunner --test-path=src
after_script:
    - coveralls
notifications:
    email: false
