language: python
python:
    - 2.6
    - 2.7
install:
    - pip install zope.testrunner --use-mirrors
    - pip install -e .
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
