language: python
dist: focal
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy2
    - pypy3
install:
    - pip install zope.testrunner coverage coverage-python-version coveralls zope.testing mock
    - pip install -e .
script:
    - coverage run --source=irclog2html -m zope.testrunner --test-path=src
after_script:
    - coveralls
    - coverage report -m
notifications:
    email: false
